;('use strict')
const configFaultAction = {
  faultsMap: {
    1: 'cellOVCritical',
    2: 'cellOVGeneral',
    3: 'cellOVMinor',
    4: 'cellUVCritical',
    5: 'cellUVGeneral',
    6: 'cellUVMinor',
    7: 'cellOTChrgCritical',
    8: 'cellOTChrgGeneral',
    9: 'cellOTChrgMinor',
    10: 'cellUTChrgCritical',
    11: 'cellUTChrgGeneral',
    12: 'cellUTChrgMinor',
    13: 'cellOTDischgCritical',
    14: 'cellOTDischgGeneral',
    15: 'cellOTDischgMinor',
    16: 'cellUTDischgCritical',
    17: 'cellUTDischgGeneral',
    18: 'cellUTDischgMinor',
    19: 'cellSOCHighCritical',
    20: 'cellSOCHighGeneral',
    21: 'cellSOCHighMinor',
    22: 'cellSOCLowCritical',
    23: 'cellSOCLowGeneral',
    24: 'cellSOCLowMinor',
    25: 'cellVSuperCritical',
    51: 'bmuOVCritical',
    52: 'bmuOVGeneral',
    53: 'bmuOVMinor',
    54: 'bmuUVCritical',
    55: 'bmuUVGeneral',
    56: 'bmuUVMinor',
    57: 'bmuOTCritical',
    58: 'bmuOTGeneral',
    59: 'bmuOTMinor',
    60: 'bmuUTCritical',
    61: 'bmuUTGeneral',
    62: 'bmuUTMinor',
    63: 'connectOTCritical',
    64: 'connectOTGeneral',
    65: 'connectOTMinor',
    66: 'connectUTCritical',
    67: 'connectUTGeneral',
    68: 'connectUTMinor',
    101: 'cellVDiffHCritical',
    102: 'cellVDiffHGeneral',
    103: 'cellVDiffHMinor',
    104: 'cellTDiffHCritical',
    105: 'cellTDiffHGeneral',
    106: 'cellTDiffHMinor',
    107: 'cellSOCDiffHCritical',
    108: 'cellSOCDiffHGeneral',
    109: 'cellSOCDiffHMinor',
    110: 'bmuVDiffHCritical',
    111: 'bmuVDiffHGeneral',
    112: 'bmuVDiffHMinor',
    131: 'clusterOVCritical',
    132: 'clusterOVGeneral',
    133: 'clusterOVMinor',
    134: 'clusterUVCritical',
    135: 'clusterUVGeneral',
    136: 'clusterUVMinor',
    137: 'R+Critical',
    138: 'R+General',
    139: 'R+Minor',
    140: 'R-Critical',
    141: 'R-General',
    142: 'R-Minor',
    143: 'chrOCCritical',
    144: 'chrOCGeneral',
    145: 'chrOCMinor',
    146: 'dischrgOCCritical',
    147: 'dischrgOCGeneral',
    148: 'dischrgOCMinor',
    149: 'envTOTCritical',
    150: 'envTOTGeneral',
    151: 'envTOTMinor',
    152: 'B+OTCritical',
    153: 'B+OTGeneral',
    154: 'B+OTMinor',
    155: 'B-OTCritical',
    156: 'B-OTGeneral',
    157: 'B-OTMinor',
    158: 'P+OTCritical',
    159: 'P+OTGeneral',
    160: 'P+OTMinor',
    161: 'P-OTCritical',
    162: 'P-OTGeneral',
    163: 'P-OTMinor',
    164: 'fuse1OTCritical',
    165: 'fuse1OTGeneral',
    166: 'fuse1OTMinor',
    167: 'fuse2OTCritical',
    168: 'fuse2OTGeneral',
    169: 'fuse2OTMinor',
    201: 'contactorFeedbackFault',
    202: 'isolationSwitchFeedbackFault',
    203: 'mainBreakerFeedbackFault',
    204: 'fanFeedbackFault',
    205: 'dcPowerKMFeedbackFault',
    206: 'doorAccessFeedbackFault',
    207: 'spdFeedbackFault',
    208: 'acVoltageFeedbackFault',
    209: 'smokeFeedbackFault',
    210: 'fireFeedbackFault',
    211: 'tempFeedbackFault',
    212: 'ventilationFeedbackFault',
    213: 'auxBreakerFeedbackFault',
    214: 'h2DetectorFeedbackFault',
    215: 'msdFeedbackFault',
    216: 'emergencyStopFeedbackFault',
    217: 'cabinetFanFeedbackFault',
    231: 'pContactorHSFeedbackFault',
    232: 'nContactorHSFeedbackFault',
    233: 'prechargeContactorHSFeedbackFault',
    234: 'redLightHSFeedbackFault',
    235: 'yellowLightHSFeedbackFault',
    236: 'greenLightHSFeedbackFault',
    237: 'fanHSFeedbackFault',
    238: 'mainBreakerHSFeedbackFault',
    239: 'dcPowerHSFeedbackFault',
    240: 'pcsControlHSFeedbackFault',
    241: 'auxBreakerHSFeedbackFault',
    242: 'airExhaustHSFeedbackFault',
    243: 'cabinetFanHSFeedbackFault',
    257: 'refrigeratorCommuFault',
    258: 'pcsCommuFault',
    259: 'dehumidifierCommuFault',
    260: 'fireCommuFault',
    261: 'bmuCommuFault',
    262: 'canHallCommuFault',
    263: 'bcuCommuFault',
    264: 'daisyChainDisconnectFault',
    265: 'afeCommuFault',
    271: 'envTSenFault',
    272: 'b+TSenFault',
    273: 'b-TSenFault',
    274: 'p+TSenFault',
    275: 'p-TSenFault',
    276: 'fuse1TSenFault',
    277: 'fuse2TSenFault',
    291: 'hallFault',
    292: 'invalidDataFault',
    293: 'framFault',
    294: 'EEPROMFault',
    295: 'FLASHFault',
    296: 'vSensorDisconnect',
    297: 'tSensorDisconnect',
    298: 'retainFaultSSummary'
  },
  faultsMapZh: {
    1: '单体过压严重总故障',
    2: '单体过压一般总故障',
    3: '单体过压轻微总故障',
    4: '单体欠压严重总故障',
    5: '单体欠压一般总故障',
    6: '单体欠压轻微总故障',
    7: '充电单体温度过高严重总故障',
    8: '充电单体温度过高一般总故障',
    9: '充电单体温度过高轻微总故障',
    10: '充电单体温度过低严重总故障',
    11: '充电单体温度过低一般总故障',
    12: '充电单体温度过低轻微总故障',
    13: '放电单体温度过高严重总故障',
    14: '放电单体温度过高一般总故障',
    15: '放电单体温度过高轻微总故障',
    16: '放电单体温度过低严重总故障',
    17: '放电单体温度过低一般总故障',
    18: '放电单体温度过低轻微总故障',
    19: '单体soc过高严重总故障',
    20: '单体soc过高一般总故障',
    21: '单体soc过高轻微总故障',
    22: '单体soc过低严重总故障',
    23: '单体soc过低一般总故障',
    24: '单体soc过低轻微总故障',
    25: '单体电压超级故障',
    51: 'BMU过压严重总故障',
    52: 'BMU过压一般总故障',
    53: 'BMU过压轻微总故障',
    54: 'BMU欠压严重总故障',
    55: 'BMU欠压一般总故障',
    56: 'BMU欠压轻微总故障',
    57: 'BMU温度过高严重总故障',
    58: 'BMU温度过高一般总故障',
    59: 'BMU温度过高轻微总故障',
    60: 'BMU温度过低严重总故障',
    61: 'BMU温度过低一般总故障',
    62: 'BMU温度过低轻微总故障',
    63: '动力接插件温度过高严重总故障',
    64: '动力接插件温度过高一般总故障',
    65: '动力接插件温度过高轻微总故障',
    66: '动力接插件温度过低严重总故障',
    67: '动力接插件温度过低一般总故障',
    68: '动力接插件温度过低轻微总故障',
    101: '单体压差过大严重故障',
    102: '单体压差过大一般故障',
    103: '单体压差过大轻微故障',
    104: '单体温差过大严重故障',
    105: '单体温差过大一般故障',
    106: '单体温差过大轻微故障',
    107: '单体SOC差异过大严重故障',
    108: '单体SOC差异大一般故障',
    109: '单体SOC差异大轻微故障',
    110: 'BMU压差过大严重故障',
    111: 'BMU压差过大一般故障',
    112: 'BMU压差过大轻微故障',
    131: '簇端过压严重故障',
    132: '簇端过压一般故障',
    133: '簇端过压轻微故障',
    134: '簇端欠压严重故障',
    135: '簇端欠压一般故障',
    136: '簇端欠压压轻微故障',
    137: '绝缘电阻正对地严重故障',
    138: '绝缘电阻正对地一般故障',
    139: '绝缘电阻正对地轻微故障',
    140: '绝缘电阻负对地严重故障',
    141: '绝缘电阻负对地一般故障',
    142: '绝缘电阻负对地轻微故障',
    143: '充电过流严重故障',
    144: '充电过流一般故障',
    145: '充电过流轻微故障',
    146: '放电过流严重故障',
    147: '放电过流一般故障',
    148: '放电过流轻微故障',
    149: '环境温度过温严重故障',
    150: '环境温度过温一般故障',
    151: '环境温度过温轻微故障',
    152: 'B+连接器温度过温严重故障',
    153: 'B+连接器温度过温一般总故障',
    154: 'B+连接器温度过温轻微故障',
    155: 'B-连接器温度过温严重故障',
    156: 'B-连接器温度过温一般总故障',
    157: 'B-连接器温度过温轻微故障',
    158: 'P+连接器温度过温严重故障',
    159: 'P+连接器温度过温一般总故障',
    160: 'P+连接器温度过温轻微故障',
    161: 'P-连接器温度过温严重故障',
    162: 'P-连接器温度过温一般总故障',
    163: 'P-连接器温度过温轻微故障',
    164: '熔断器1温度过温严重故障',
    165: '熔断器1温度过温一般故障',
    166: '熔断器1温度过温轻微故障',
    167: '熔断器2温度过温严重故障',
    168: '熔断器2温度过温一般故障',
    169: '熔断器2温度过温轻微故障',
    201: '接触器总故障',
    202: '隔离开关反馈故障',
    203: '主断路器反馈故障',
    204: '风扇控制反馈故障',
    205: '直流供电KM反馈故障',
    206: '门禁反馈故障',
    207: 'SPD反馈故障',
    208: '交流电压反馈故障',
    209: '烟感反馈故障',
    210: '消防反馈故障',
    211: '温感反馈故障',
    212: '排风系统反馈故障',
    213: '辅助断路器反馈故障',
    214: '氢气（H2）探测器反馈故障',
    215: 'MSD信号反馈故障',
    216: '急停反馈故障',
    217: '柜体风机反馈故障',
    231: '主正高边驱动反馈故障',
    232: '主负高边驱动反馈故障',
    233: '预充高边驱动反馈故障',
    234: '红灯高边驱动反馈故障',
    235: '黄灯高边驱动反馈故障',
    236: '绿灯高边驱动反馈故障',
    237: '风机高边驱动反馈故障',
    238: '主断分励高边驱动反馈故障',
    239: '直流供电高边驱动反馈故障',
    240: 'PCS封波高边驱动反馈故障',
    241: '辅助断路器分励高边反馈故障',
    242: '排风系统高边反馈故障',
    243: '柜体风机高边反馈故障',
    257: '制冷设备通讯故障',
    258: 'PCS设备通讯故障',
    259: '除湿机通讯故障',
    260: '消防设备通讯故障',
    261: 'BMU通讯故障',
    262: 'CAN霍尔通讯故障',
    263: 'BCU对上通讯故障',
    264: '菊花链断连故障',
    265: 'AFE通讯故障',
    271: '环境温度传感器故障',
    272: 'B+连接器温度传感器故障',
    273: 'B-连接器温度传感器故障',
    274: 'P+连接器温度传感器故障',
    275: 'P-连接器温度传感器故障',
    276: '熔断器1温度传感器故障',
    277: '熔断器2温度传感器故障',
    291: '霍尔故障',
    292: '存在无效数据',
    293: '铁电存储器故障',
    294: 'EEPROM故障',
    295: 'FLASH故障',
    296: '电压采集掉线',
    297: '温度采集掉线',
    298: '保留故障汇总点'
  },
  totalFaultsMap: {
    contactor: [
      'pContactorFeedbackFault',
      'pContactorHSFeedbackFault',
      'pContactorOxidation',
      'pContactorAdhesion',
      'pContactorFaultSummary',
      'nContactorFeedbackFault',
      'nContactorHSFeedbackFault',
      'nContactorOxidation',
      'nContactorAdhesion',
      'nContactorFaultSummary',
      'prechargeContactorFeedbackFault',
      'prechargeContactorHSFeedbackFault',
      'prechargeContactorOxidation',
      'prechargeContactorAdhesion',
      'prechargeContactorFaultSummary',
      'reserved'
    ],
    invalidValue1: [
      'cellVoltInvalid',
      'cellTempInvalid',
      'cellSOCInvalid',
      'packVoltInvalid',
      'bmuBordTempInvalid',
      'PoleT1TempInvalid',
      'PoleT2TempInvalid',
      'clusterTemp1Invalid',
      'clusterTemp2Invalid',
      'clusterTemp3Invalid',
      'clusterTemp4Invalid',
      'clusterTemp5Invalid',
      ...Array.from({ length: 4 }, () => 'reserved')
    ],
    cellFault: {
      fault: [
        'cellOV',
        'cellUV',
        'cellOTChrg',
        'cellUTChrg',
        'cellOTDischg',
        'cellUTDischg',
        'cellSOCHigh',
        'cellSOCLow'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    },
    packFault: {
      fault: ['packOV', 'packUV', 'packOT', 'packUT', 'Pole1OT', 'Pole2OT', 'reserved', 'reserved'],
      level: ['无故障', '严重', '一般', '轻微']
    },
    clusterFault1: {
      fault: [
        'cellVDiff',
        'cellTDiff',
        'cellSOCDiff',
        'bmuVDiff',
        'clusterOV',
        'clusterUV',
        'R+',
        'R-'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    },
    clusterFault2: {
      fault: ['chargOC', 'dischrgOC', 'rt1OT', 'rt2OT', 'rt3OT', 'rt4OT', 'rt5OT', 'reserved'],
      level: ['无故障', '严重', '一般', '轻微']
    },
    cellFaultEvent: {
      fault: [
        '单体电压过压',
        '单体电压欠压',
        '单体充电过温',
        '单体充电欠温',
        '单体放电过温',
        '单体放电欠温',
        '单体SOC过高',
        '单体SOC过低'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    },
    packFaultEvent: {
      fault: [
        'pack电压过压',
        'pack电压欠压',
        'pack温度过温',
        'pack温度欠温',
        '动力接插件1过温',
        '动力接插件2过温',
        '预留',
        '预留'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    },
    clusterFault1Event: {
      fault: [
        '单体电压差过大',
        '单体温度差过大',
        '单体SOC差过大',
        'BMU电压差过大',
        '簇过压',
        '簇欠压',
        '绝缘电阻正对地过低',
        '绝缘电阻负对地过低'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    },
    clusterFault2Event: {
      fault: [
        '充电过流',
        '放电过流',
        'RT1过温',
        'RT2过温',
        'RT3过温',
        'RT4过温',
        'RT5过温',
        '预留'
      ],
      level: ['无故障', '严重', '一般', '轻微']
    }
  },
  didoTMap: {
    diSignal1: [
      'mainPosFeedback',
      'mainNegFeedback',
      'prechargeFeedback',
      'isolationSwitchFeedback',
      'mainBreakerFeedback',
      'fanFeedback',
      'dcPowerKMFeedback',
      'doorAccessFeedback',
      'spdFeedback',
      'acVoltageFeedback',
      'smokeFeedback',
      'fireFeedback',
      'tempFeedback',
      'ventilationFeedback',
      'auxBreakerFeedback',
      'h2DetectorFeedback'
    ],
    diSignal2: [
      'msdFeedback',
      'emergencyStopFeedback',
      'cabinetFanFeedback',
      ...Array.from({ length: 13 }, () => 'reversed')
    ],
    doSignal1: [
      'pContactorHSFeedback',
      'nContactorHSFeedback',
      'prechargeContactorHSFeedback',
      'greenLightHSFeedback',
      'yellowLightHSFeedback',
      'redLightHSFeedback',
      'fanHSFeedback',
      'mainBreakerHSFeedback',
      'dcPowerHSFeedback',
      'pcsControlHSFeedback',
      'auxBreakerHSFeedback',
      'airExhaustHSFeedback',
      'cabinetFanHSFeedback',
      ...Array.from({ length: 3 }, () => 'reversed')
    ],
    doControlSignal1: [
      'pContactorControl',
      'nContactorControl',
      'prechargeContactorControl',
      'greenLightControl',
      'yellowLightControl',
      'redLightControl',
      'fanControl',
      'mainBreakerControl',
      'dcPowerKMControl',
      'pcsControl',
      'auxBreakerControl',
      'airExhaustControl',
      'cabinetFanControl',
      ...Array.from({ length: 3 }, () => 'reversed')
    ],

    rtData: {
      0: 'empty',
      1: 'bcuTemp',
      2: 'b+Temp',
      3: 'b-Temp',
      4: 'p+Temp',
      5: 'p-Temp',
      6: 'fuse1Temp',
      7: 'fuse2Temp'
    },
    rtDataZh: {
      0: '空配置',
      1: 'BCU环境温度',
      2: 'B+温度',
      3: 'B-温度',
      4: 'P+温度',
      5: 'P-温度',
      6: '熔断器1温度',
      7: '熔断器2温度'
    }
  }
}

export { configFaultAction }
